# Generated by Django 4.2.3 on 2023-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=1000)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('preference_lingustique', models.CharField(max_length=255)),
                ('compte_par_defaut', models.IntegerField(null=True)),
                ('nombre_connexions', models.IntegerField(default=0)),
                ('mailbox', models.CharField(default='E-mail', max_length=200)),
                ('mot_de_passe', models.CharField(max_length=1000)),
                ('login', models.IntegerField(unique=True)),
            ],
        ),
    ]
