# Generated by Django 4.2.3 on 2023-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='compte_par_defaut',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
