# Generated by Django 4.2.3 on 2023-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_utilisateur_compte_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='compte_par_defaut',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
