# Generated by Django 4.2.3 on 2023-07-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_utilisateur_compte_par_defaut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
