# Generated by Django 4.2.3 on 2023-07-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_utilisateur_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='preference_lingustique',
            new_name='preference_linguistique',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='compte_par_defaut',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='login',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('num_compte', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=200, unique=True)),
                ('date_solde', models.DateField()),
                ('solde', models.IntegerField()),
                ('alerte_mail', models.CharField(max_length=200)),
                ('alerte_sms', models.CharField(max_length=200)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.utilisateur')),
            ],
        ),
    ]
