# Generated by Django 4.2.3 on 2023-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_utilisateur_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_a_debiter', models.CharField(max_length=255)),
                ('compte_a_crediter', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_payment', models.TextField()),
                ('date_execution', models.DateField()),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit'), ('avec_beneficiaire', 'Avec Bénéficiaire')], max_length=20)),
                ('beneficiaire', models.CharField(default='aucun', max_length=255)),
                ('nom_raison_sociale', models.CharField(default='aucun', max_length=255)),
                ('banque', models.CharField(default='aucun', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirementPermanant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_exec', models.IntegerField()),
                ('periodicite', models.CharField(max_length=100)),
                ('premier_virement_annee', models.PositiveIntegerField(blank=True, null=True)),
                ('premier_virement_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('dernier_virement_annee', models.PositiveIntegerField(blank=True, null=True)),
                ('dernier_virement_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('compte_a_debiter', models.CharField(max_length=255)),
                ('compte_a_crediter', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_payment', models.TextField()),
                ('date_execution', models.DateField()),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit'), ('avec_beneficiaire', 'Avec Bénéficiaire')], max_length=20)),
                ('beneficiaire', models.CharField(default='aucun', max_length=255)),
                ('nom_raison_sociale', models.CharField(default='aucun', max_length=255)),
                ('banque', models.CharField(default='aucun', max_length=255)),
            ],
        ),
    ]
