# Generated by Django 4.2.3 on 2023-07-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_virement_virementpermanant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virement',
            name='compte_a_crediter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_a_crediter', to='bankapp.compte'),
        ),
        migrations.AlterField(
            model_name='virement',
            name='compte_a_debiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_a_debiter', to='bankapp.compte'),
        ),
        migrations.AlterField(
            model_name='virementpermanant',
            name='compte_a_crediter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_permanents_credites', to='bankapp.compte'),
        ),
        migrations.AlterField(
            model_name='virementpermanant',
            name='compte_a_debiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_permanents_debites', to='bankapp.compte'),
        ),
    ]
