# Generated by Django 4.2.3 on 2023-07-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_virement_compte_a_crediter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='virementpermanant',
            name='type',
        ),
    ]
