# Generated by Django 4.2.3 on 2023-07-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_remove_virement_type_remove_virementpermanant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virementpermanant',
            name='date_execution',
        ),
    ]
