# Generated by Django 4.2.3 on 2023-07-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_remove_virementpermanant_date_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tel', models.IntegerField()),
                ('message', models.TextField()),
                ('system_exploitation', models.CharField(max_length=100)),
                ('service_pack', models.CharField(max_length=100)),
                ('navigateur', models.CharField(max_length=100)),
                ('fournisseur_internet', models.CharField(max_length=100)),
                ('communication', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=1000)),
                ('agence', models.CharField(max_length=1000)),
                ('numero_tel', models.IntegerField()),
                ('message_erreur', models.TextField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.utilisateur')),
            ],
        ),
    ]
