# Generated by Django 4.2.3 on 2023-07-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_message_support_message_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_agence',
            old_name='message_erreur',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message_support',
            old_name='message',
            new_name='message_erreur',
        ),
    ]
