# Generated by Django 4.2.3 on 2023-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0013_rename_message_erreur_message_agence_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_support',
            name='numero_fax',
            field=models.IntegerField(default='000'),
        ),
    ]
